Revert "run CI with Ruby 3.4"
This reverts commit fcdb4466760d593e5771cefe6f1af28d30277d1d.

On Ruby 3.4.1, the specs fail with lines like these:

  NoMethodError:
    undefined method 'deprecate_methods' for class ActiveSupport::Deprecation
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext/module/deprecation.rb:23:in 'Module#deprecate'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext/range/deprecated_conversions.rb:32:in '<module:DeprecatedRangeWithFormat>'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext/range/deprecated_conversions.rb:4:in '<module:ActiveSupport>'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext/range/deprecated_conversions.rb:3:in '<top (required)>'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext/range.rb:4:in '<top (required)>'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext.rb:5:in 'block in <top (required)>'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext.rb:3:in 'Array#each'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/core_ext.rb:3:in '<top (required)>'
  # /home/roadster/.gem/ruby/3.4.1/gems/activesupport-7.0.8.7/lib/active_support/all.rb:5:in '<top (required)>'
  # ./spec/support/ext_verifier.rb:6:in 'block in ExtVerifier.require_dependencies!'
  # ./spec/support/ext_verifier.rb:5:in 'Array#each'
  # ./spec/support/ext_verifier.rb:5:in 'ExtVerifier.require_dependencies!'
  # ./spec/spec_helper.rb:30:in '<top (required)>'
  # ./spec/misc_spec.rb:5:in '<top (required)>'